# Generated by Django 4.2.8 on 2025-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_add_salarys'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
