# Generated by Django 4.2.8 on 2025-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_add_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_booking',
            name='Phone_Number',
            field=models.CharField(max_length=20),
        ),
    ]
